### ISSUE TITLE
New release for PHP 8.1 compatibility

### ISSUE THREAD

**Issue by gjportegies** [elgentos/magento2-alternate-urls#8]
I noticed that there is already a MR that adds PHP 8.1 compatibility.
Is it possible to create a new release including this MR?

Thanks in advance!

**Comment by peterjaap** [comment]
@ArjenMiedema ?

**Comment by ArjenMiedema** [comment]
I'll update the extension to also support the latest Magento version and create a tag

**Comment by ArjenMiedema** [comment]
@gjportegies you can now use tag 1.2.1 with Magento 2.4.4 and above and PHP 8.1 and above.
